## Pokémon

Pokémon (ポケモン Pokemon?) é uma franquia de mídia que pertence a The Pokémon Company, tendo sido criada por Satoshi Tajiri em 1995.Ela é centrada em criaturas ficcionais chamadas "Pokémon", que os seres humanos capturam e os treinam para lutarem entre si com seus ataques de diversos tipos.

A franquia começou com um par de jogos lançados para o Game Boy original, desenvolvidos pela Game Freak e publicados pela Nintendo. Atualmente, a franquia se estende em jogos, cartas colecionáveis, série de televisão, além de filmes, mangás e brinquedos. Pokémon é a segunda franquia de mídia de jogos mais bem sucedida e lucrativa do mundo, atrás da franquia de Mario que também pertence a Nintendo.

Em 2006, a franquia celebrou seu aniversário de 10 anos. As vendas dos jogos (incluindo home console games, como Hey You, Pikachu!, para Nintendo 64) acumularam mais de 200 milhões de cópias vendidas. Em novembro de 2005, a 4Kids Entertainment, que tinha conseguido o licenciamento da série animada, anunciou que havia concordado em não renovar o contrato da representação da franquia. A Pokémon USA Inc. (atualmente The Pokémon Company International), uma subsidiária da japonesa Pokémon Co., passou a supervisionar todas as licenças de Pokémon fora da Ásia. Até 2013, a franquia de Pokémon acumulou 4 trilhões ao redor do mundo (equivalente a 40,98 bilhões de dólares).

#### Nome  

O nome Pokémon é uma abreviação da marca japonesa Pocket Monsters (ポケットモンスター Poketto Monsutā?). O termo Pokémon, além de se referir a própria franquia Pokémon, também se refere às mais de 900 espécies de ficção que aparecem na mídia de Pokémon. A palavra "Pokémon" é usada no singular e plural para o nome individual de cada espécie; a gramática correta é "um Pokémon" e "muitos Pokémon", bem como "um Pikachu" e "muitos Pikachu". No entanto, em Pokémon Red, Blue e Yellow, alguns NPCs se referiam a Clefairy e Diglett no plural, mostrando "CLEFAIRYs" and "DIGLETTs", respectivamente. Isso foi arrumado em FireRed e LeafGreen.

#### Concepção  

Uma história animada de como Satoshi Tajiri chegou a conceber "Pokémon".Tajiri teve a ideia de Pokémon por volta de 1989 ou 1990, quando o Game Boy foi lançado. O conceito do universo Pokémon foi inspirado no passatempo do diretor executivo Satoshi Tajiri de colecionar insetos quando era criança, Então como as crianças estavam prestando mais atencão aos videogames do que a brincar ao ar livre (Ou fazer isso) Ele decidiu fazer um videogame onde as crianças podiam fazer isso, Mas com monstros! Os jogadores dos jogos são chamados de Treinadores Pokémon e dois dos principais objetivos (na maioria dos jogos Pokémon) para os Treinadores são: completar a Pokédex, capturando todas as espécies Pokémon disponíveis; e treinar seu time de Pokémon para competir contra o time de outros Treinadores e, eventualmente, se tornar o mais forte Treinador: um Mestre Pokémon. O conceito de capturar, treinar e batalhar estão presentes em quase todas as versões da franquia Pokémon, incluindo nos jogos, no anime e na série de mangá, e no jogo de cartas.

Na maioria dos jogos de Pokémon, um Treinador que encontra um Pokémon selvagem é capaz de capturá-lo através de um objeto esférico chamado Pokébola. Se o Pokémon não escapar da Pokébola, ele é considerado oficialmente do Treinador. Em seguida, o Pokémon irá obedecer todos os comandos do seu mestre, a menos que o Treinador não tenha muita experiência, a ponto dele preferir agir por conta própria. Os Treinadores podem mandar seus Pokémon para batalhas contra outros Pokémon; se o Pokémon adversário é selvagem, é possível capturá-lo com uma Pokébola, aumentando o seu time de Pokémon. No entanto, os Pokémon já pertencentes a outros Treinadores não podem ser capturados, exceto sob circunstâncias especiais em certos jogos. Se um Pokémon derrota o adversário durante uma batalha, então o oponente é nocauteado (ou seja, "desmaia"). O Pokémon vencedor ganha pontos de experiência e, às vezes, pode subir de nível. Quando um Pokémon sobe de nível, as suas estatísticas de batalha são aumentadas. Os Pokémon também podem aprender novos ataques, que são técnicas usadas nas batalhas. Além disso, muitas espécies de Pokémon possuem a capacidade de evoluir e se transformar em uma espécie mais forte.

Nas séries principais, o modo single-player de cada jogo requer que o Treinador tenha um time Pokémon para derrotar muitos Treinadores não jogáveis (NPC) e seus Pokémon. Cada jogo apresenta um caminho linear através de uma região específica do mundo Pokémon para o Treinador viajar, competindo em eventos e batalhando contra oponentes ao longo do caminho. Cada jogo possui oito Treinadores especialmente fortes, referidos como Líderes de Ginásio, que o Treinador deve derrotar a fim de progredir. Como recompensa, o Treinador recebe uma Insígnia de Ginásio e, conseguido todas as oito insígnias, aquele Treinador pode batalhar na Liga Pokémon da região. Na Liga Pokémon se encontram quatro Treinadores imensamente talentosos (referidos coletivamente como "Elite Four"), que desafiam o Treinador para quatro batalhas Pokémon sucessivas. Se o Treinador conseguir derrotá-los, ele deve desafiar o Campeão Regional, o Treinador Mestre que, anteriormente, venceu a Elite Four. Qualquer Treinador que vence essa última batalha se torna o novo campeão.

Na sétima geração (Sun & Moon e UltraSun & UltraMoon), os tradicionais líderes de ginásios foram substituídos por Trial Captains que, com o mesmo intuito dos ginásios, possuem desafios, puzzles e batalhas para que o treinador possa prosseguir em sua jornada. A sétima geração manteve o conceito de Elite Four e Champion League.

### Jogos  

Ver artigo principal: Pokémon (série de jogos eletrônicos).  

#### Gerações  

Os jogos originais de Pokémon foram role-playing (RPGs) com elementos de estratégia e foram criados por Satoshi Tajiri para o Game Boy. Esses RPGs, e suas sequências, remakes e traduções em inglês, são ainda considerados os "principais" jogos de Pokémon, além de serem os jogos que os fãs da série geralmente se referem quando usam o termo "jogos de Pokémon". Todas as propriedades Pokémon licenciadas são supervisionadas pela The Pokémon Company International, sendo divididas por gerações. Essas gerações são cronologicamente divididas pelo seu lançamento; a cada determinado número de anos, quando uma sequência oficial nas séries RPGs principais é lançada, contendo novos Pokémon, personagens e conceitos de jogabilidade, aquela sequência é considerada o começo de uma nova geração da franquia. Os jogos principais e os spin-offs, anime, mangá e cartas colecionáveis são atualizados com as novas propriedades de Pokémon toda vez que uma nova geração começa. A sétima geração da franquia começou em 18 de novembro de 2016.


#### Batalha entre um Charmander e um Bulbasaur no Pokémon Red e Pokémon Blue  

#### Primeira geração  

A origem de Pokémon está em dois jogos chamados Poketto Monsutā Midori, mais conhecido como Pokémon Green, e Poketto Monsuttā Aka, conhecido no ocidente por Pokémon Red, lançados em 1996, no Japão. Pokémon Green nunca foi lançado fora do Japão, sendo lançado apenas Pokémon Red Version e Blue Version. Pokémon Blue também foi lançado no Japão, alguns meses após o lançamento dos dois primeiros. Devido ao sucesso destes jogos, os quais chegaram a ser alguns dos jogos mais vendidos do Japão em 1996, houve a produção de uma versão diferente, denominada Pokémon Yellow: Special Pikachu Edition; trazia como Pokémon principal um Pikachu que andava sempre seguindo o jogador fora de sua Pokébola. Pokémon Red & Blue vendeu mais de dez milhões de cópias no Ocidente e Pokémon Yellow vendeu mais de cinco milhões de cópias sozinho.

Pokémon não foi lançado apenas para o Game Boy; mas também para o Nintendo 64, com três jogos especialmente para o console: um chamado Pokémon Stadium, que usava monstrinhos transferidos do Game Boy ou contidos no próprio Stadium em batalhas 3D, além de trazer uma série de minigames. Outro foi um spin-off chamado Hey You, Pikachu!, que inovou ao implementar nos videogames o sistema de microfone. O terceiro jogo foi Pokémon Snap, onde o jogador controlava um fotógrafo de Pokémon e devia fotografá-los da melhor maneira possível. Houve ainda um spin-off da série para o Game Boy chamado Pokémon Pinball, que trazia um pinball usando Pokémon e também foi um dos poucos jogos do console a usar a função "rumble", que fazia o console vibrar ao fazer certos movimentos.

#### Segunda geração  

À medida que conquistava cada vez mais fãs mundialmente, os criadores decidiram fazer uma continuação dos primeiros jogos. Isso gerou em duas novas versões, que traziam uma aventura diferente das anteriores, situada em uma Região ao lado do palco dos primeiros jogos, 100 novos Pokémon, totalizando 251, recursos novos, entre outros. Conhecidos como Pokémon Gold & Silver, eles serviram de base para o mecanismo dos seguintes, apresentando a distinção entre Pokémon machos e fêmeas, possibilitando o cruzamento de Pokémon, conceito muito usado para trocas entre jogadores, utilizando o tempo dentro do jogo, diferenciando o dia da noite e muitas outras novidades para os jogadores. Foram os jogos eletrônicos mais vendidos de 2000 e os mais vendidos do Game Boy Color. O terceiro jogo ficou conhecido como Pokémon Crystal Version e destacava o Pokémon lendário Suicune. Apresentava das outras duas versões, alguns detalhes novos com mudanças na parte gráfica, animações dos desenhos dos Pokémon ao começarem uma batalha e era o único jogo da segunda geração em que havia a possibilidade de conseguir o lendário Celebi.

Para o Nintendo 64 houve uma nova versão de Pokémon Stadium conhecida no ocidente como Pokémon Stadium 2, que trazia os 251 Pokémon em 3D e as mesmas mecânicas, além de novos minigames, uma característica marcante da série Stadium. Depois de Stadium 2 houve mais alguns spin-offs da série, como Pokémon Puzzle Challenge, Pokémon Puzzle League, ambos do mesmo gênero de jogos, sendo um para o Game Boy Color e o outro para o Nintendo 64; ainda foram lançados Pokémon Trading Card Game e Pokémon Trading Card Game 2, jogos que se baseavam no Trading Card Game da série.

#### Terceira geração  

Em março de 2003, foram lançados os primeiros jogos da terceira geração, mais conhecida pelos jogadores como geração Advance, já que seus RPGs originais eram feitos para o portátil Game Boy Advance: Pokémon Ruby & Sapphire, que ultrapassaram as 3,1 milhões de unidades vendidas, sendo assim os mais comercializados no Japão em 2002 traziam 135 novos Pokémon, mas era impossível transferir Pokémon de gerações anteriores para os jogos, pois o treinamento deles em Pokémon Ruby & Sapphire se baseava em um outro sistema, o de Effort Values (valores de esforço), pontos que, ao serem bem calculados e distribuídos ao Pokémon, deixavam-no mais forte que outros treinados sem esse método. Para conseguir alguns dos Pokémon antigos, Pokémon Ruby & Sapphire conectava-se com outros jogos de terceira geração, principalmente Pokémon Colosseum, um dos jogos do tipo plataforma daquela geração.

Em 2004, Pokémon Red & Green ganharam remakes para o Game Boy Advance e foram lançados como Pokémon FireRed & LeafGreen. FireRed & LeafGreen voltava ao cenário dos primeiros jogos e refazia a jornada deles. Com isso, trazia a possibilidade de obtenção de todos os 150 primeiros e também um aspecto de nostalgia, sendo refeitos quase que exatamente como os primeiros jogos. Os remakes também traziam uma nova área para o mundo Pokémon: as Sevii Islands, onde era possível achar e capturar monstrinhos que eram nativos de Johto, palco dos jogos de segunda geração. Foram os jogos mais vendidos da Nintendo entre 2004 e 2005.

Os jogos do tipo plataforma tiveram uma atenção especial na Geração Advance, tendo dois jogos com modos nunca vistos na série Stadium. Pokémon Colosseum foi lançado em 2004 no Japão, junto com FireRed & LeafGreen, e foi o primeiro jogo de plataforma da série com um modo RPG. Este modo RPG trazia uma nova região, conhecida como Orre, onde um garoto tinha que salvar Pokémon com uma aura maligna corroendo seus corações, denominados Shadow Pokémon (inglês para Pokémon sombrio), e capturá-los de treinadores e membros de uma organização criminosa conhecida como Cipher. Em Colosseum, esse garoto tem que viajar por Hoenn ao lado de uma garota, a única pessoa que pode distinguir Pokémon normais dos Shadow Pokémon. Após capturá-los, ele tem que usá-los em batalhas para diminuir sua "barra de coração" (em inglês, Hearth Gauge) até o fim, possibilitando o Shadow Pokémon tornar-se novamente um Pokémon comum. Pokémon Colosseum foi dado como um grande jogo de Pokémon, embora desaconselhável para jogadores novatos. No ano seguinte, 2005, foi lançado Pokémon XD: Gale of Darkness, continuação direta de Colosseum, onde um novo herói tem que salvar Orre dos Cipher, que voltaram das sombras e se reorganizaram, criando um Shadow Pokémon que não poderia ser purificado, conhecido pelo codinome de XD001. Pokémon XD foi avaliado como uma versão melhorada de Colosseum, mas apresentava as mesmas falhas do antecessor. Ambos os jogos foram lançados para o Nintendo GameCube.

Em 2005, a geração Advance termina com Pokémon Emerald. Emerald era uma versão complementar para Ruby & Sapphire e trazia novos recursos, como o retorno das animações dos Pokémon ao início das batalhas, conceito já usado em Pokémon Crystal, uma nova área repleta de desafios chamada Battle Frontier e também a possibilidade, através de eventos, de capturar Mew sem a necessidade de truques, como em Red, Blue e Yellow. Foi o segundo jogo mais vendido do Japão em 2005.

A terceira geração trouxe mais spin-offs à série, como Pokémon Pinball Ruby & Sapphire, um novo pinball de Pokémon, usando os 202 Pokémon presentes em Ruby & Sapphire e a compatibilidade com o acessório e-Reader, Pokémon Channel, um spin-off que simulava uma estação de televisão comandada por, e feita para, Pokémon, e Pokémon Box Ruby & Sapphire, avaliado mais como um organizador de Pokémon vindos de Ruby & Sapphire, FireRed & LeafGreen e Emerald, com capacidade de armazenamento de até 1.500 monstrinhos em um só cartão de memória.

#### *Spin-offs*

Entre a terceira e quarta geração de RPGs Originais de Pokémon, *spin-offs* foram feitos especialmente para o Nintendo DS. O primeiro foi Pokémon Dash em 2005, no qual havia corridas entre os Pokémon em percursos a pé ou de balão usando a Stylus, a caneta do DS. Em 2006, nos Estados Unidos, foram lançados mais três spin-offs. Pokémon Trozei! trazia um puzzle usando Pokémon, em um tabuleiro onde se tentava alinhar quatro monstrinhos iguais para eliminá-los e ganhar pontos. Em um estilo mais cartoon e semelhante ao jogo PaneldePon, Pokémon Trozei! foi dado como divertido por usar a Stylus de um modo dinâmico e inteligente. Depois de Pokémon Trozei!, foi lançado Pokémon Mystery Dungeon (também feito para o Game Boy Advance), onde o jogador é um humano transformado em Pokémon em um mundo composto apenas com eles, onde é necessário salvar a todos da destruição por uma maldição, resgatando Pokémon que precisam de ajuda e desvendando os mistérios que resultaram na transformação do protagonista em Pokémon. Por último, veio Pokémon Ranger, um jogo que introduzia uma nova forma de controlar os Pokémon, obtendo-os apenas por um tempo e soltando-os depois na natureza. Em Pokémon Ranger, o jogador tinha que usar os Pokémon de modo correto para derrotar uma organização maléfica que pretende capturar, aprisionar e usar os Pokémon para destruir as civilizações de todo o mundo. Pokémon Ranger também ganhou uma continuação onde pode-se capturar Darkrai em uma missão especial.

Cada um desses jogos apresentava um ou mais Pokémon de quarta geração: Pokémon Dash apresentou aos jogadores Munchlax, a forma pré-evoluída do Pokémon de primeira geração Snorlax. Pokémon Mystery Dungeon introduziu Bonsly (embora ele já tivesse aparecido em Pokémon XD), Mime Jr., Weavile e Lucario, sendo apenas Lucario um Pokémon completamente novo. E Pokémon Ranger mostrou aos jogadores um dos Pokémon Lendários de quarta geração, conhecido como Manaphy.

#### Quarta geração  

Em setembro de 2006, foram lançados no Japão as duas primeiras versões de RPGs originais da quarta geração de Pokémon, feitas para o Nintendo DS. Pokémon Diamond & Pearl introduziram 106 novos Pokémon, totalizando 493, novas funções, como uma mudança na parte dos ataques, divindindo-os em três tipos (Physical, que usa o valor Attack; Special, que usa o valor Special Attack e Other, que utiliza qualquer outro valor), a volta das mudanças de horário entre o dia e a noite, usado pela última vez em Pokémon Gold & Silver, incluindo a possibilidade de conexão online através da Nintendo Wi-Fi Connection, onde os jogadores de qualquer parte do mundo poderiam batalhar e trocar Pokémon com vários outros jogadores do planeta. Também introduziu no Nintendo DS o uso de um fone de ouvido que permitia conversas entre os jogadores que iriam se enfrentar na Nintendo WFC. Pokémon Diamond & Pearl venderam mais de 1,58 milhão de cópias nos quatro primeiros dias no Japão e também foram os jogos mais vendidos do país em todo o ano de 2006. Nos Estados Unidos Pokémon Diamond & Pearl venderam mais de um milhão de cópias na primeira semana de vendas e mais de dez no mundo inteiro.

Em dezembro de 2006, chegou às lojas do Japão o primeiro jogo de plataforma da série para o console Wii: Pokémon Battle Revolution. Ele estabelece uma conexão com Pokémon Diamond & Pearl, de modo que os Pokémon de Diamond & Pearl podem ser transferidos para Pokémon Battle Revolution. Battle Revolution também traz a possibilidade de usar Pokémon diretamente de Diamond & Pearl para batalhas em 3D com amigos e copiá-los para o jogo para serem usados para a completação de coliseus (Colosseums) em um lugar chamado Pokétopia ou usá-los através de Nintendo Wi-Fi Connection também.

A quarta geração teve apenas dois spin-off já anunciados. É a seqüência direta de Pokémon Mystery Dungeon, chamada Pokémon Mystery Dungeon 2 e também sequência de outro jogo Pokémon Ranger: Shadows of Almia. Também foi anunciado que a série Pokémon ganharia seu primeiro jogo de arcade, denominado Pokémon Battrio. A sequência de Pokémon Mystery Dungeon foi lançada em 13 de setembro de 2007.

Em 2008, foi lançado o terceiro jogo de RPG da quarta geração, Pokémon Platinum, que no seu segundo dia de vendas no Japão, já havia vendido 963 mil unidades. Trazendo uma nova dimensão para Sinnoh, o mundo distorcido (The Distortion World), onde é possível encontrar Giratina.

Em 12 de setembro de 2009 foi colocado à venda no Japão, remakes dos jogos Pokémon Gold & Silver para o Nintendo DS intitulado Pokémon HeartGold & SoulSilver. Assim como Pokémon Yellow, que somente Pikachu andava fora da Poké-bola, qualquer Pokémon que seja o primeiro de sua equipe anda ao seu lado agora. E duas novas áreas para Johto, uma espécie de pokémon Safari e também traz de volta o Battle Frontier. Vem acompanhando também o Pokéwalker.

#### Quinta geração

O Pokéwalker, um pedômetro que conta os seus passos e se conecta com o DS
Em 29 de janeiro de 2010, a Pokémon Company anunciou que o novo jogo Pokémon, que traz os primeiros monstrinhos da quinta geração, estava em desenvolvimento para o Nintendo DS a ser lançado no final daquele mesmo ano.

O anúncio da revelação foi feito no site da TV Tokyo, onde foi postado que "Os novos jogos Pokémon XY finalmente serão revelados!".

Os nomes das versões da 5ª geração são: Pokémon Black e Pokémon White! A revelação foi feita pela página oficial dos monstrinhos. Mais detalhes virão no dia 15, mas as informações divulgadas mostram que o lançamento acontecerá no outono japonês. Como esperado, o primeiro grande destaque são os gráficos 3D que estão melhores desenvolvidos em relação às versões anteriores. Em seguida, temos a nova tela de batalha, como mostra a imagem com Zorua e Zoroark, os primeiros monstrinhos da nova geração. O Centro Pokémon recebeu um upgrade e agora possui um balcão de vendas, possivelmente resultado de uma fusão com os Mercado Pokémon. Notem, na mesma imagem, que agora é mostrada uma indicação de qual personagem está falando, como se fosse um balão de histórias em quadrinhos. Temos também os sprites em miniatura dos dois treinadores principais. A garota usa um boné branco e rosa e rabo-de-cavalo, enquanto o garoto possui um boné branco e vermelho com uma roupa azul. Mas informações são esperadas no Pokémon Sunday, que será exibido hoje, e nos próximos dias, na atualização do site oficial. Os iniciais são de Planta Snivy,o de fogo Tepig e o de água o Oshawott. além de outros como os dois lendários Reshiram e Zekrom. E outros como Minccino, Munna, Klink, Pidove, Darmanitan, Blitzle e Sandile. Foram lançados no total 157 novos Pokémon nesta geração.

Pokémon Black 2 e Pokémon White 2 são lançados em 2012 no Japão dando continuação ao enredo de Pokémon Black e Pokémon White após dois anos.

#### Sexta geração

Os novos jogos Pokémon X & Y são anunciados para Outubro de 2013 agora para uma nova plataforma, o Nintendo 3DS, na região de Kalos. Os três novos Pokémon iniciais são Fennekin (fogo), Chespin (grama) e Froakie (água) e os Pokémon lendários Xerneas (Pokémon X) e Yveltal (Pokémon Y) com uma nova experiência de jogo em 3D. Este foi o jogo que mais surpreendeu de toda a franquia com muitas novidades inéditas, a começar pela que mais surpreendeu: As Mega Evoluções, que são versões evoluídas de alguns Pokémon. Ela é uma evolução temporária, assim, ela só acontece durante uma batalha se o Pokémon segura a sua respectiva Mega Stone (o item que o faz mega evoluir). Já mega evoluídos, os Pokémon podem ter uma alteração nos status, nas habilidades e até no tipo. É importante lembrar que só um Pokémon pode mega evoluir por batalha. Outra grande novidade foi a adição do tipo fada, que conta com novos Pokémon e até alguns antigos que tiveram este tipo adicionado ou substituído pelo antigo, como é o caso de Togekiss, que era do tipo normal/voador e virou do tipo fada/voador. Este tipo foi criado com o intuito de balancear o jogo do lado competitivo que na geração passada era dominado pelos dragões, já que fada tem vantagem e imunidade a dragão.

Sétima geração
Durante uma apresentação do Nintendo Direct em 26 de fevereiro de 2016, dois novos títulos de Pokémon foram anunciados: Pokémon Sun e Pokémon Moon. Os Primeiros Jogos da sétima geração de Pokémon, com previsão para lançamento em dezembro de 2016 mas, lançado oficialmente em Novembro do mesmo ano. Os jogos serão compatíveis com outros títulos Nintendo 3DS, incluindo Pokémon X e Y; Pokémon Omega Ruby e Alpha Sapphire; e o Virtual Console de re-lançamentos de Pokemon Red, Blue e Yellow.

Em maio de 2016 foi revelado o nome da nova região a ser explorada, Alola, uma arquipélago inspirado no Hawaii, bem como os três novos Pokémon iniciais: Rowlet, dos tipos grama e voador; Litten, do tipo fogo e Popplio, do tipo água. Também foram reveladas as artes de capa com os Pokémon lendários mascotes de cada versão: Solgaleo na versão Sun, dos tipos psíquico e metal, e Lunala na versão Moon, dos tipos psíquico e fantasma. Porém, seus nomes e tipos só vieram a ser divulgados no início de junho de 2016.

Os jogos Pokémon Ultra Sun e Ultra Moon, anunciados em 6 de junho de 2017, foram lançados no dia 17 de novembro.

#### Oitava geração  

Em 27 de fevereiro de 2019, os primeiros jogos da franquia no Nintendo Switch, Pokémon Sword e Shield, foram anunciados. Os três Pokémon iniciais revelados no trailer são Scorbunny, de fogo, Sobble, de água, e Grookey, de grama. Os lendários macotes são Zacian, na versão Sword, e Zamazenta, na versão Shield.

Em um Nintendo Direct, foi revelado que nem todos os Pokémon iriam estar no jogo, o que deixou muitos fãs irritados; como consequência, foram criadas as hashtags #BringBackNationalDex (Tragam de volta a National Dex) e #BBND. Em 3 de junho de 2020, foram anunciadas as DLCs Pokémon Isle of Armor e Pokémon Crown of Tundra.

#### Nona geração  

Em 27 de fevereiro de 2022, Pokémon Scarlet e Violet foram anunciados para o Nintendo Switch, com data de lançamento para 2022.

#### Mecânica   

Ver artigo principal: Jogabilidade de Pokémon
Treinador Pokémon. Os jogadores são chamados de Treinador Pokémon. Seu objetivo é alcançar dois objetivos (na maioria dos jogos de Pokémon): capturar todas as espécies de Pokémon disponíveis na região fictícia onde o jogo está configurado e completar a informação de todos os Pokémon na Pokédex; Por outro lado, eles devem treiná-los e enfrentar outros Pokémon pertencentes a outros treinadores para demonstrar suas habilidades, força, talento e assim se tornar um "Mestre de Pokémon". Para conseguir isso, o treinador Pokémon viajam por todas as regiões do mundo dos Pokémon, coletando "insígnias de ginásio", que são obtidas após derrotar o respectivo Líderes de Ginásio, em uma batalha na qual ambos treinadores e o líder de ginásio enfrentam seus Pokémon para testar suas habilidades especiais em uma batalha Pokémon.

#### Pokémon inicial  

Uma árvore de Natal com vários Pokémon iniciais, incluindo Pikachu, Plusle e Minum
Um dos aspectos constantes dos videojogos Pokémon desde a sua criação com Pokémon Red e Pokémon Blue (no Ocidente) para o console portátil Game Boy, até as versões mais recentes, é que os jogadores, no início do jogo, recebem seus primeiros Pokémon como um presente de um Professor (isso depende da região onde o jogo está definido), um personagem especialista em Pokémon.

Os treinadores recebem um Pokémon inicial para começar sua jornada no jogo. A quantidade estabelecida de iniciais Pokémon é três, das quais os treinadores podem escolher apenas um. Eles são sempre do tipo grama, tipo fogo e tipo água, um Pokémon por tipo. Por exemplo, nas versões Pokémon Red e Blue (e seus respectivos remakes, Pokémon FireRed e LeafGreen), o jogador tem a opção de escolha entre Bulbasaur (tipo grama), Charmander (tipo de fogo) e Squirtle (tipo de água).

No entanto, em Pokémon Yellow, o treinador recebe como seu Pokémon inicial o Pikachu (famoso por ser o mascote da franquia e um Pokémon do tipo elétrico). No entanto, após os lançamentos da Pokémon Red e Pokémon Blue, Pikachu pode ser obtido durante sua busca na trajetória do jogo por um único jogador, algo que não foi possível em qualquer outra entrega da franquia, até o lançamento do Pokémon X e Pokémon Y. Outro aspecto constante é que o rival do jogador, um personagem que também se torna um treinador ao mesmo tempo que o jogador, sempre escolherá um Pokémon que tenha uma vantagem sobre o do protagonista. Por exemplo: se o jogador escolher um Pokémon tipo grama, o oponente sempre escolherá um Pokémon tipo fogo como seu Pokémon inicial. Em Pokémon Yellow, o oponente escolhe Eevee, que pode ser evoluído para um Jolteon, Vaporeon, ou Flareon, dependendo do resultado da batalha entre o jogador e o adversário no laboratório Pokémon e um outro evento especifico.

#### Pokédex  

A Pokédex no mundo fictício dos Pokémon é um dispositivo eletrônico que intervém nos videogames e nas séries de anime. Nos jogos, sua função é registrar os dados de um Pokémon. No mangá e no anime, a Pokédex é uma enciclopédia eletrônica que fornece ao treinador informações sobre um Pokémon que é desconhecido. Para utilizá-la, o treinador apenas precisa expor a Pokédex na frente dos Pokémon.

Nos jogos de vídeo, um treinador recebe uma Pokédex em branco no início de sua jornada. O objetivo é completar a informação de todos os Pokémon disponíveis na região onde você está. O treinador receberá o nome e a imagem do Pokémon que foi encontrado. Em Pokémon Red & Blue, a Pokédex registra a informação de cada Pokémon com apenas ver. A informação mais detalhada sobre um Pokémon está disponível depois que o treinador capturou um Pokémon selvagem. Esta informação inclui tipo, altura, peso, técnicas e uma breve descrição dos Pokémon.

As versões atuais da Pokédex contêm todas as informações dos conhecidos pokémon. Nos jogos de GameCube, Pokémon Colosseum e Pokémon XD: Gale of Darkness, o Pokémon Digital Assistant (PDA) é usado, o que é semelhante ao Pokédex.

Atualmente a Pokédex Nacional vai do Pokémon número #001 (Bulbasaur) até o #807 (Zeraora).

Fonte: [Wikipedia](https://pt.wikipedia.org/wiki/Pok%C3%A9mon)